version: '3'

services:
  beerus-rpc:
    image: "beerus:${BEERUS_VERSION:-latest}"
    ports:
      - '3030:3030'
      - '3031:3031'
    environment:
      ETHEREUM_NETWORK: "mainnet"
      ETHEREUM_CONSENSUS_RPC_URL: "https://www.lightclientdata.org"
      ETHEREUM_EXECUTION_RPC_URL: "https://eth-mainnet.g.alchemy.com/v2/spl1o-SnCzLfKdNt-_-BxQ0lsJmR3FLU"
      STARKNET_RPC_URL: "https://starknet-mainnet.infura.io/v3/a77771c7226a447bada27e682ae743bd"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "200M"
        reservations:
          cpus: "0.25"
          memory: "200M"
