name: continuous integration

on:
  pull_request:

# The following urls will soon be removed, API keys invalidated and RPC urls will be provided as secrets

env:
  BEERUS_VERSION: ci
  ETHEREUM_NETWORK: mainnet
#  ETHEREUM_CONSENSUS_RPC_URL: ${{ secrets.ETHEREUM_CONSENSUS_RPC_URL }}
  ETHEREUM_CONSENSUS_RPC_URL: https://www.lightclientdata.org
#  ETHEREUM_EXECUTION_RPC_URL: ${{ secrets.ETHEREUM_EXECUTION_RPC_URL }}
  ETHEREUM_EXECUTION_RPC_URL: https://eth-mainnet.g.alchemy.com/v2/nveGwZH-6VJciyEwZb3C1iblkZWj3Fcj
#  STARKNET_RPC_URL: ${{ secrets.STARKNET_RPC_URL }}
  STARKNET_RPC_URL: https://starknet-mainnet.infura.io/v3/a77771c7226a447bada27e682ae743bd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code
      - name: Checkout
        uses: actions/checkout@v3
      # Setup docker
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Build and export the beerus docker image
      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: beerus:${{ env.BEERUS_VERSION }}
          outputs: type=docker,dest=/tmp/beerus.tar
      # Upload the beerus docker image as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: beerus
          path: /tmp/beerus.tar

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout the source code
      - name: Checkout
        uses: actions/checkout@v3
      # Install hurl
      - name: Install dependencies
        run: |
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/2.0.1/hurl_2.0.1_amd64.deb
          sudo apt-get update && sudo apt-get install -y ./hurl_2.0.1_amd64.deb
      # Download the beerus docker image
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: beerus
          path: /tmp
      # Load the beerus docker image
      - name: Load docker image
        run: |
          docker load --input /tmp/beerus.tar
          docker image ls -a
      # Run beerus RPC in the background
      - name: Run beerus
        run: |
          docker run -d -p 3030:3030 -p 3031:3031 --env ETHEREUM_NETWORK="mainnet" --env ETHEREUM_CONSENSUS_RPC_URL="https://www.lightclientdata.org" --env ETHEREUM_EXECUTION_RPC_URL="https://eth-mainnet.g.alchemy.com/v2/spl1o-SnCzLfKdNt-_-BxQ0lsJmR3FLU" --env STARKNET_RPC_URL="https://starknet-mainnet.infura.io/v3/a77771c7226a447bada27e682ae743bd" beerus:ci
          hurl --retry --retry-max-count 60 ./examples/beerus-rpc/starknet/starknet_blockNumber.hurl > /dev/null;
      # Execute hurl tests
#      - name: Execute the end-to-end tests
#        id: e2e_test
#        run: |
#          ./e2e-tests.sh
#        continue-on-error: true
      # Execute every hurl apart
      - name: Run hurl tests
        run: |
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_getStorageAt.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_getTransactionReceipt.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_getTransactionCount.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_syncing.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_getBalance.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_getCode.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_gasPrice.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_getLogs.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_getTransactionByBlockHashAndIndex.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_sendRawTransaction.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_coinbase.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_getBlockTransactionCountByNumber.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_chainId.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_blockNumber.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_getTransactionByHash.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_call.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_getBlockTransactionCountByHash.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_getBlockByHash.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_getBlockByNumber.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_maxPriorityFeePerGas.hurl
          hurl --test --max-time=30 examples/beerus-rpc/eth/eth_estimateGas.hurl
          hurl --test --max-time=30 examples/beerus-rpc/additional/starknet_l1_to_l2_message_nonce.hurl
          hurl --test --max-time=30 examples/beerus-rpc/additional/starknet_l1_to_l2_messages.hurl
          hurl --test --max-time=30 examples/beerus-rpc/additional/starknet_addDeployAccountTransaction.hurl
          hurl --test --max-time=30 examples/beerus-rpc/additional/starknet_addDeclareTransaction.hurl
          hurl --test --max-time=30 examples/beerus-rpc/additional/starknet_l2_to_l1_messages.hurl
          hurl --test --max-time=30 examples/beerus-rpc/additional/starknet_getContractStorageProof.hurl
          hurl --test --max-time=30 examples/beerus-rpc/additional/starknet_addInvokeTransaction.hurl
          hurl --test --max-time=30 examples/beerus-rpc/additional/starknet_l1_to_l2_message_cancellations.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_getClassHashAt.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_getClassAt.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_getEvents.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_chainId.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_getEstimateFee.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_getClass.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_getTransactionByHash.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_getBlockTransactionCount.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_getTransactionByBlockIdAndIndex.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_getStorageAt.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_blockNumber.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_getBlockWithTxs.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_blockHashAndNumber.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_syncing.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_getNonce.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_call.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_pendingTransactions.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_getStateUpdate.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_getBlockWithTxHashes.hurl
          hurl --test --max-time=30 examples/beerus-rpc/starknet/starknet_getTransactionReceipt.hurl
      # Capture docker logs
      - name: Capture docker logs
        run: |
          docker ps
          docker logs $(docker ps -q) >& docker_logs.txt
          cat docker_logs.txt
      # Upload the docker logs
      - name: Upload docker logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: docker-logs
          path: docker_logs.txt
      # Generate job summary
      - name: Generate job summary
        run: cat summary.md >> $GITHUB_STEP_SUMMARY
      # Fail the job if the script step has failed
      - name: Check for script failure
        run: |
          if [[ "${{ steps.e2e_test.outcome }}" == "failure" ]]; then
            exit 1
          fi
